### ISSUE TITLE
RuntimeError: Unable to open /content/drive/My Drive/Colab Notebooks/LipNet-master/../common/predictors/shape_predictor_68_face_landmarks.dat

### ISSUE THREAD

**Issue by ola512-aa** [rizkiarm/LipNet#123]
can any one help me to  solve this problem ??
!python predict.py evaluation/models/overlapped-weights368.h5 evaluation/samples/id2_vcd_swwp2s.mpg

2021-08-05 21:48:07.043957: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0

Loading data from disk...
Traceback (most recent call last):
  File "predict.py", line 60, in <module>
    video, result = predict(sys.argv[1], sys.argv[2])
  File "predict.py", line 27, in predict
    video.from_video(video_path)
  File "/content/drive/My Drive/Colab Notebooks/LipNet-master/lipnet/lipreading/videos.py", line 121, in from_video
    self.handle_type(frames)
  File "/content/drive/My Drive/Colab Notebooks/LipNet-master/lipnet/lipreading/videos.py", line 132, in handle_type
    self.process_frames_face(frames)
  File "/content/drive/My Drive/Colab Notebooks/LipNet-master/lipnet/lipreading/videos.py", line 138, in process_frames_face
    predictor = dlib.shape_predictor(self.face_predictor_path)
RuntimeError: Unable to open /content/drive/My Drive/Colab Notebooks/LipNet-master/../common/predictors/shape_predictor_68_face_landmarks.dat

**Comment by Mr-Usama** [comment]
-the problem is missing the ( shape_predictor_68_face_landmarks.dat ) file.
- download and paste in the project directory and again give the path, this will resolve the issue.
- 
 file link : https://github.com/italojs/facial-landmarks-recognition/blob/master/shape_predictor_68_face_landmarks.dat
