### ISSUE TITLE
Error in training using random_split

### ISSUE THREAD

**Issue by sanaullahmanzoor1988** [rizkiarm/LipNet#2]
Epoch 1/20
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py", line 606, in data_generator_task
    generator_output = next(self._generator)
TypeError: 'threadsafe_iter' object is not an iterator

Traceback (most recent call last):
  File "train.py", line 72, in <module>
    train(run_name, 0, 20, 3, 100, 50, 75, 32, 50)
  File "train.py", line 68, in train
    pickle_safe=False)
  File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\legacy\interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\bismil\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\engine\training.py", line 1851, in fit_generator
    str(generator_output))
ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

**Comment by Foursmall** [comment]
when I run the default demo with command "./predict evaluation/models/weights04.h5  evaluation/samples/id2_vcd_swwp2s.mpg ",Error"ValueError: Dimension 0 in both shapes must be equal, but are 512 and 256 for 'Assign_12' (op: 'Assign') with input shapes: [512,768], [256,768]."happened.
Could you tell me resolution ?Thank you sincerely!

**Comment by rizkiarm** [comment]
``RandomSplitGenerator`` is currently unmaintained, you may do a PR if you want.
The second problem is related to #3. I've just updated the weight and it should be working now.
