### ISSUE TITLE
Runtime Error during prediction

### ISSUE THREAD

**Issue by WrathofBhuvan11** [rizkiarm/LipNet#71]
Loading data from disk...
Traceback (most recent call last):
  File "/home/...../LipNet/predict.py", line 60, in <module>
    video, result = predict(sys.argv[1], sys.argv[2])
  File "/home/...../LipNet/predict.py", line 27, in predict
    video.from_video(video_path)
  File "/home/...../LipNet/lipnet/videos.py", line 174, in from_video
    self.handle_type(frames)
  File "/home/...../LipNet/lipnet/videos.py", line 185, in handle_type
    self.process_frames_face(frames)
  File "/home/..../LipNet/lipnet/videos.py", line 191, in process_frames_face
    predictor = dlib.shape_predictor(self.face_predictor_path)
RuntimeError: Unable to open /home/...../LipNet/../common/predictors/shape_predictor_68_face_landmarks.dat

**Comment by JaxSulav** [comment]
Put the path value of face_predictor_path = r"PATH/to/shape_predictor_68_face_landmarks.dat" in videos.py. It will work

**Comment by chahatagarwal** [comment]
> Loading data from disk...
> Traceback (most recent call last):
> File "/home/...../LipNet/predict.py", line 60, in
> video, result = predict(sys.argv[1], sys.argv[2])
> File "/home/...../LipNet/predict.py", line 27, in predict
> video.from_video(video_path)
> File "/home/...../LipNet/lipnet/videos.py", line 174, in from_video
> self.handle_type(frames)
> File "/home/...../LipNet/lipnet/videos.py", line 185, in handle_type
> self.process_frames_face(frames)
> File "/home/..../LipNet/lipnet/videos.py", line 191, in process_frames_face
> predictor = dlib.shape_predictor(self.face_predictor_path)
> RuntimeError: Unable to open /home/...../LipNet/../common/predictors/shape_predictor_68_face_landmarks.dat

Remove ".." from the path of face predictor variable in predict.py script
