### ISSUE TITLE
Problem while running extract_mouth_batch.py

### ISSUE THREAD

**Issue by riya-maan** [rizkiarm/LipNet#72]
On running extract_mouth_batch.py I'm getting following error:

Using TensorFlow backend.
Processing: datasets/s1/prwq3s.mpg
Traceback (most recent call last):
  File "scripts/extract_mouth_batch.py", line 47, in <module>
    video = Video(vtype='face', face_predictor_path=FACE_PREDICTOR_PATH).from_video(filepath)
  File "/Users/riyamaan/Desktop/LipNet/lipnet/lipreading/videos.py", line 120, in from_video
    frames = self.get_video_frames(path)
  File "/Users/riyamaan/Desktop/LipNet/lipnet/lipreading/videos.py", line 196, in get_video_frames
    frames = np.array([frame for frame in videogen])
  File "/Users/riyamaan/Desktop/LipNet/lipnet/lipreading/videos.py", line 196, in <listcomp>
    frames = np.array([frame for frame in videogen])
  File "/Users/riyamaan/anaconda3/lib/python3.6/site-packages/skvideo/io/io.py", line 251, in vreader
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/Users/riyamaan/anaconda3/lib/python3.6/site-packages/skvideo/io/ffmpeg.py", line 194, in __init__
    self.inputframenum = np.int(check_output(probecmd).split('\n')[0])
TypeError: a bytes-like object is required, not 'str'

How to resolve it?

**Comment by riya-maan** [comment]
Updated sk-video. It works fine then.
