### ISSUE TITLE
TypeError: 'threadsafe_iter' object is not an iterator

### ISSUE THREAD

**Issue by CXiaoDing** [rizkiarm/LipNet#81]
I run the "train.py", and this error arises, how can I solve it???

**Comment by CXiaoDing** [comment]
Traceback (most recent call last):
  File "/home/cxd/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 635, in data_generator_task
    generator_output = next(self._generator)
TypeError: 'threadsafe_iter' object is not an iterator
Epoch 1/5000
Traceback (most recent call last):
  File "/home/cxd/PycharmProjects/LipNet-master/training/unseen_speakers/train.py", line 78, in <module>
    train(run_name, 0, 5000, 3, 100, 50, 75, 32, 50)
  File "/home/cxd/PycharmProjects/LipNet-master/training/unseen_speakers/train.py", line 74, in train
    pickle_safe=True)   #喂入数据，开始训练
  File "/home/cxd/anaconda3/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/cxd/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 2116, in fit_generator
    generator_output = next(output_generator)
  File "/home/cxd/anaconda3/lib/python3.6/site-packages/keras/utils/data_utils.py", line 735, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/cxd/anaconda3/lib/python3.6/site-packages/six.py", line 686, in reraise
    raise value
TypeError: 'threadsafe_iter' object is not an iterator

Process finished with exit code 1

**Comment by shoaibkh** [comment]
I face same problem can you help me that how u can resolve it @CXiaoDing ?

**Comment by sindhura234** [comment]
@shoaibkh @CXiaoDing Did you guys resolve it?
