### ISSUE TITLE
is this supposed to be run on python 2?

### ISSUE THREAD

**Issue by akouminov** [rizkiarm/LipNet#99]
it seems that this should be run on python 2, please add in read me if so

**Comment by iares777** [comment]
I also think this is for python 2, but installation error:       File "c:\users\ares\appdata\local\temp\easy_install-ioi9x4\numpy-1.18.3\setup.py", line 32, in <module>
        # these are required to build h5py
    RuntimeError: Python version >= 3.5 required.
![1](https://user-images.githubusercontent.com/60398219/80739771-6fe21500-8b30-11ea-8061-3c3db7bdeace.png)

**Comment by jeonsanghun** [comment]
> it seems that this should be run on python 2, please add in read me if so

I am now catching an error to change this code running in Python 2.7 to Python 3.6.
If the code runs in 3.6, can you share it?

**Comment by akouminov** [comment]
I have a version that I modified if you would like to take a look
akoumino/LipNet

**Comment by jeonsanghun** [comment]
> I have a version that I modified if you would like to take a look
> akoumino/LipNet

Can I receive it by e-mail? (jeon7887@gmail.com)
Is it correct with python 3.x and running fine?

**Comment by nmstoker** [comment]
@jeonsanghun - I think this is what you were after:
https://github.com/akouminov/LipNet

_Akouminov had accidentally missed a "v" out of his username name earlier_

**Comment by arindam999** [comment]
Hi @akouminov - running your code but running into following error. Any help ? 


!./predict evaluation/models/overlapped-weights368.h5 evaluation/samples/id2_vcd_swwp2s.mpg



2020-09-21 02:55:54.328514: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

Loading data from disk...
Data loaded.

WARNING:tensorflow:From /content/LipNet/LipNet/lipnet/model2.py:15: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.

2020-09-21 02:56:04.498704: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-21 02:56:04.558177: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:04.558868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2020-09-21 02:56:04.558911: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-21 02:56:04.558966: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-21 02:56:04.706921: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-21 02:56:04.707073: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-21 02:56:04.707102: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-21 02:56:04.733860: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-21 02:56:04.733997: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-21 02:56:04.734122: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:04.734888: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:04.735482: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-21 02:56:04.735846: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-21 02:56:04.751132: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2000165000 Hz
2020-09-21 02:56:04.751413: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x26ffb80 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-21 02:56:04.751459: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-09-21 02:56:04.896747: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:04.897515: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0xb058380 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-09-21 02:56:04.897572: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-16GB, Compute Capability 7.0
2020-09-21 02:56:04.898950: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:04.899536: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:00:04.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.75GiB deviceMemoryBandwidth: 836.37GiB/s
2020-09-21 02:56:04.899621: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-21 02:56:04.899659: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2020-09-21 02:56:04.899682: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2020-09-21 02:56:04.899695: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2020-09-21 02:56:04.899708: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2020-09-21 02:56:04.899721: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2020-09-21 02:56:04.899734: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2020-09-21 02:56:04.899798: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:04.900359: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:04.900911: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
2020-09-21 02:56:04.906025: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-21 02:56:08.762899: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-09-21 02:56:08.762957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 
2020-09-21 02:56:08.762966: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N 
2020-09-21 02:56:08.769087: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:08.769850: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:982] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-21 02:56:08.770436: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2020-09-21 02:56:08.770503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14756 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:04.0, compute capability: 7.0)
Traceback (most recent call last):
  File "/content/LipNet/LipNet/evaluation/predict.py", line 60, in <module>
    video, result = predict(sys.argv[1], sys.argv[2])
  File "/content/LipNet/LipNet/evaluation/predict.py", line 53, in predict
    y_pred         = lipnet.predict(X_data)
  File "/content/LipNet/LipNet/lipnet/model2.py", line 75, in predict
    return self.test_function([input_batch, 0])[0]  # the first 0 indicates test
  File "/content/LipNet/LipNet/lipnet/model2.py", line 80, in test_function
    return K.function([self.input_data, K.learning_phase()], [self.y_pred, K.learning_phase()])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/backend.py", line 3936, in function
    model = models.Model(inputs=inputs, outputs=outputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 242, in __new__
    return functional.Functional(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 115, in __init__
    self._init_graph_network(inputs, outputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/functional.py", line 142, in _init_graph_network
    base_layer_utils.create_keras_history(self._nested_outputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 191, in create_keras_history
    _, created_layers = _create_keras_history_helper(tensors, set(), [])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py", line 226, in _create_keras_history_helper
    op = tensor.op  # The Op that created this Tensor.
AttributeError: 'int' object has no attribute 'op'

**Comment by jainnimish** [comment]
It can only run on Python 3.5 to Python 3.7 because TensorFlow only supports these versions of python as of October 2020.

**Comment by akouminov** [comment]
@arindam999 , have run into this before, this is an environment issue, if you still need it I can look into it for you
